[doc.html.body.main]
attrib = {class="material-symbols-outlined"}
h1 = "Attrib"
blocks = [
    '''
    The doors are beeping. So nobody is speaking. And now the doors open and the beeping stops.
    ''',
    '''
    <Chalgrove>     The benches are all wet.
    ''',
    '''
    <Bullingdon>    Well, I fancy a smoke anyway. We'll wait for him through there.
    ''',
    '''
    On the street.
    ''',
    '''
    <Appleby>       Found you.
    ''',
    '''
    <Chalgrove>     I was about to send a message.
    ''',
    '''
    <Appleby>       The seating was wet, so I came out here.
    ''',
]
