[doc.html.body.main]
attrib = {class="material-symbols-outlined"}
h1 = "Attrib"
blocks = [
    '''
    The *attrib* parameter specifies attributes for the current tag:
    ''',
    '''
    `[[doc.html.head.meta]]`

    `attrib = {{name = "viewport", content = "width=device-width, initial-scale=1.0"}}`
    ''',
    '''
    Results in:

    `<meta name="viewport" content="width=device-width, initial-scale=1.0" />`
    ''',
]
