[doc.html.body.main]
blocks = [
    '''
    Everyone has stopped talking. After three seconds the doors open and the dialogue picks up again.
    ''',
    '''
    <Chalgrove>     The benches are all wet.
    ''',
    '''
    <Bullingdon>    Well, I fancy a smoke anyway. We'll wait for him through there.
    ''',
    '''
    On the street.
    ''',
    '''
    <Appleby>       Found you.
    ''',
    '''
    Nods of acknowledgement all round.
    ''',
    '''
    <Chalgrove>     I was about to send a message.
    ''',
    '''
    <Appleby>       The seating was wet, so I came out here.
    ''',
]
