[doc.html.body.main]
blocks = [
    '''
    <Chalgrove>     Are you well?
    ''',
    '''
    <Appleby>       For the most part.

    Very concerned about the situation right now though.
    ''',
    '''
    <Bullingdon>    Indeed.
    ''',
    '''
    <Chalgrove>     There's really no trusting anybody is there?
    ''',
    '''
    <Bullingdon>    You knew what you were getting into.
    ''',
    '''
    <Appleby>       Yes, up to a point.
    ''',
    '''
    <Chalgrove>     We had our concerns too of course. I mean, we spoke about it.

    But it did all seem to be going in the right direction.
    ''',
    '''
    <Appleby>       The idea that there's a straight path to anywhere is an illusion.
    ''',
]

