[base]
config = {tag_mode = "open"}
"!doctype html" = ""

[base.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[base.html.head]
title = "{metadata[title]}"

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {charset = "UTF-8"}

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="basics.css"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="layout.css"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="object.css"}

[base.html.body.header]
attrib = {popovertarget = "nav-upper"}
button = "≡"  # "IDENTICAL TO" (U+2261)

[base.html.body.header.nav]
attrib = {id="nav-upper", popover = "auto"}

[[base.html.body.header.nav.ul.li]]
attrib = {class = "card"}

[base.html.body.header.nav.ul.li.div.img]
config = {tag_mode = "void"}
attrib = {src = "zen-509371_640.jpg", alt="Close up on the face of a Zen Buddha statue"}

[base.html.body.header.nav.ul.li.div.span]
attrib = {href = "a.html"}
a = "Gathering"

[base.html.body.header.nav.ul.li.div]
p = "Three acquaintances meet at a conjunction of the Way."

[[base.html.body.header.nav.ul.li]]
attrib = {class = "card"}

[base.html.body.header.nav.ul.li.div.img]
config = {tag_mode = "void"}
attrib = {src = "lion-671193_640.jpg", alt="Close up on the face of a Stone Lion statue"}

[base.html.body.header.nav.ul.li.div.span]
attrib = {href = "b.html"}
a = "Council"

[base.html.body.header.nav.ul.li.div]
p = "Trouble is brewing. There is danger to one of the protagonists."

[[base.html.body.header.nav.ul.li]]
attrib = {class = "card"}

[base.html.body.header.nav.ul.li.div.img]
config = {tag_mode = "void"}
attrib = {class = "spiki hflip", src = "bull-statue-7482855_640.jpg", alt="Close up on the face of a Bronze Bull statue"}

[base.html.body.header.nav.ul.li.div.span]
attrib = {href = "c.html"}
a = "Resolve"

[base.html.body.header.nav.ul.li.div]
p = "The bond is strengthened by adversity. They commence the next move forward together."

[base.html.body.main]
config = {tag_mode = "pair", block_wrap = "div"}

[[base.html.body.footer.nav.ul.li]]
attrib = {class = "spiki home", href = "index.html"}
a = "Next"

