[base]
config = {tag_mode = "open"}
"!doctype html" = ""

[base.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[base.html.head]
title = "{metadata[title]}"

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {charset = "UTF-8"}

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[base.html.head.meta]]
config = {tag_mode = "void"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="basics.css"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="layout.css"}

[[base.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="object.css"}

[[base.html.body.nav.header.ul.li]]
attrib = {class = "spiki home", href = "index.html"}
a = "Basic Example"

[base.html.body.main]
config = {tag_mode = "pair", block_wrap = "div"}
