# Node '5'

[metadata]
title = "Completion"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "6401.html"}
a = "Revisit"

[doc.html.body.main]
blocks = [
"""
<Chalgrove>     Appleby is happy hunting around anyway.
<Appleby>       I'll need you to keep making notes though.
                This mystery might run deep. I'm likely to get lost in it otherwise.
""",
"""
Much of the earlier antagonism has been forgotten.
A healthy degree of mutual respect is making its welcome return.
""",
"""
<Broadstairs>   OK, is it time for another round?
<Appleby>       Let's [keep moving](6401.html). I'd like to try further down the street.
"""
]
