# Node '5'

[metadata]
title = "Completion"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "6401.html"}
a = "Revisit"

[doc.html.body.main]
blocks = [
"""
Describe the feeling of hope.
Lots of discovery to be done
""",
"""
<Chalgrove>     OK, is it time for another round?
<Broadstairs>   Let's [keep moving](6401.html). I'd like to try further down the street.
"""
]
