# Node '7'

[metadata]
title = "Defaulted"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "6003.html"}
a = "Revisit"

[doc.html.body.main]
blocks = [
"""
A lovely stone promenade gives a view over the park.
They pass through an iron gate and stand for a moment at the conjunction of two tree-lined avenues.
The paths down to the river flank a cultivated pool and a pretty public garden.
""",
"""
<Broadstairs>   We can let Appleby run around here for a bit before we head back.
<Chalgrove>     If we follow the track down and then left, it will lead us [to the station](6003.html).
<Broadstairs>   Very well.
""",
]
