# Node '8'

[metadata]
title = "Withdrawn"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "6127.html"}
a = "Revisit"

[doc.html.body.main]
blocks = [
"""
<Appleby>       I don't really want to hang around much longer.
<Chalgrove>     I'm afraid we might be short on time.
<Broadstairs>   Shall we withdraw? I've no desire to be late again.
""",
"""
Slightly unfulfilled, they [turn back](6127.html) the way they came.
""",
]
