# Edge 'd'

[metadata]
title = "Adoption"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0842.html"}
a = "Completion"

[doc.html.body.main]
blocks = """
<Chalgrove>     Human action is repetitious. We establish a routine and it propagates to others.
<Broadstairs>   Yes, and the vocabulary evolves accordingly. New words are created, or older ones get repurposed.
<Appleby>       But here we've encountered a semantic token with no apparent reference. Which implies an entire
                process of action which hitherto we've been unaware of.
<Chalgrove>     So I'm classifying this as a Phantasm. For the moment, at least.
<Appleby>       OK, and whatever else we encounter will simply accrete. Until we glimpse its nature.
<Broadstairs>   Then our own vocabulary will adjust to explain it.
<Chalgrove>     A new case then?
<Broadstairs>   A new case. Top priority. Happy now, Appleby?
"""
