# Edge 'j'

[metadata]
title = "Withdrawal"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0848.html"}
a = "Withdrawn"

[doc.html.body.main]
blocks = [
"""
<Appleby>       I thought we were here to explore. That's the whole point of a visit, isn't it?
<Chalgrove>     Yes, explore. But maybe another time when things are less weird.
<Broadstairs>   You want to [head off home](0848.html) now and come back later?
<Chalgrove>     I think so.
<Appleby>       Well I think we're wasting an opportunity.
""",
]
