# Edge 'n'

[metadata]
title = "Cancellation"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0850.html"}
a = "Cancelled"

[doc.html.body.main]
blocks = """
A bell rings at the bar.

<Appleby>       What was that?
<Broadstairs>   I think they've just called time.
<Chalgrove>     Is it that late already?
"""
