# Edge 'p'

[metadata]
title = "Revisit"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0834.html"}
a = "Inception"

[doc.html.body.main]
blocks = [
"""
<Chalgrove>     I find it very calming, walking by the river. No traffic.
<Appleby>       Although coming this way, we're missing some of the sights. But what's this?
""",
"""
The zeal of the clergy and the ambitions of architects extend beyond the construction of mere churches.
Hence this Georgian gaol. The pews here, arguably more comfortable. The hangings decidedly less decorative.
""",
"""
<Broadstairs>   This is a prison.
<Appleby>       So it is.
<Chalgrove>     Not far now. Down the end of the road, and we'll be at the rear of [the station](0834.html).
""",
]
