# Edge 'r'

[metadata]
title = "Revisit"

[[doc.html.body.footer.nav.ul.li]]
attrib = {class = "spiki next", href = "0834.html"}
a = "Inception"

[doc.html.body.main]
blocks = [
"""
<Broadstairs>   Are you comfortable heading back through the town?
<Chalgrove>     I think we had best avoid the areas of greatest anomaly.
<Appleby>       After me then.
""",
"""
Appleby follows his nose. It appears to him that some of the oldest buildings are mounting a resistance
to the encroachment of the Phantasm. They were standing at the time of Kepler and Newton.
They refuse to allow the Natural Principles to fall.

And so it happens that they troop past a grand Anglican church.
The font in that place has bathed a very famous figure of the Enlightenment.

But Chalgrove can spare no time for that today. It's all he can do to hide his anxiety that they soon
[reach the station](0834.html).
""",
]
