[metadata]
title = "Custom Plugins"

[doc]
config = {tag_mode = "open"}
"!doctype html" = ""

[doc.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[doc.html.head]
title = "{metadata[title]}"

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {charset = "UTF-8"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="speech.css"}

[doc.html.body.main]
blocks = """
This example shows how to extend Spiki with your own plugin.

The custom code is in the file
[templater.py](https://github.com/thuswise/spiki/blob/main/spiki/examples/eclectic/templater.py).
The plugin is invoked by the CLI options in
[spiki.cli](https://github.com/thuswise/spiki/blob/main/spiki/examples/eclectic/spiki.cli).

It uses the speech block as a template and creates new dialogue by
substituting data from a
[local file](https://github.com/thuswise/spiki/blob/main/spiki/examples/eclectic/orders.csv).

"""

[[doc.html.body.main.section]]
blocks = ["""
*A man walks into a hardware store*...
"""]

[[doc.html.body.main.section]]
define = {file = "orders.csv", index = 0, quantity = 0, product = "?", punc = "", reply = "OK", rows = [{}]}
blocks = ["""
<Customer>  {define[product]}{define[punc]}
<Shopkeep>  {define[product]}. {define[reply]}. {define[rrp]}.

*({define[file]} row {define[index]})*
"""]
