[metadata]
title = "Tabular data"

[doc]
config = {tag_mode = "open"}
"!doctype html" = ""

[doc.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[doc.html.head]
title = "{metadata[title]}"

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {charset = "UTF-8"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="speech.css"}

[doc.html.body.main]
blocks = """
This example demonstrates use of a non-standard plugin.

A Speech template is populated from an ancillary file.

"""

[[doc.html.body.main.section]]
define = {file = "orders.csv", index = 0, quantity = 0, product = "?", reply = "OK", rows = [{}]}
blocks = ["""
<Customer>  {define[quantity]} {define[product]}
<Shopkeep>  {define[reply]}

*({define[file]} row {define[index]})*
"""]
