# https://raw.githubusercontent.com/Bowserinator/Periodic-Table-JSON/refs/heads/master/periodic-table-lookup.json

[metadata]

[doc]
config = {tag_mode = "open"}
"!doctype html" = ""

[doc.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[doc.html.head]
title = "{metadata[title]}"

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {charset = "UTF-8"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "preconnect", href = "https://fonts.googleapis.com"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = "crossorigin"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "stylesheet", href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100..900;1,100..900&display=swap"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "stylesheet", href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&display=swap"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="app.css"}

[[doc.html.head.script]]
attrib = {src = "https://unpkg.com/hyperscript.org@0.9.14", async = "async"}

[doc.html.body.main]
blocks = """
This is an example of an interactive HTML5 application.
It uses [Hyperscript](https://hyperscript.org/), which is a lightweight Javascript library.
Spiki facilitates the *locality of behaviour* approach.

Click the button below to download the data for the Periodic Table of Elements.
"""

[[doc.html.body.main.section]]
button = "Get Data"

[doc.html.body.main.section.attrib]
id = "btn_fetch"
script = """
init add @disabled to #inp_pick
on click
add @disabled
fetch https://raw.githubusercontent.com/Bowserinator/Periodic-Table-JSON/refs/heads/master/periodic-table-lookup.json
as json
set global data to result
finally
remove @disabled
remove @disabled from #inp_pick
"""

[[doc.html.body.main.section]]
blocks = """
Type the name of an element to display its properties.
"""

[doc.html.body.main.section.input]
config = {tag_mode = "void"}

[doc.html.body.main.section.input.attrib]
id = "inp_pick"
script = """
on input
for word in data["order"]
if my.value is not empty and word contains my.value.toLowerCase()
put data[word].name into <dd.name/>
put data[word].number into <dd.number/>
put data[word].atomic_mass into <dd.mass/>
break
"""

[[doc.html.body.main.dl.div]]
attrib = { class = "name field" }
dt = "Name"
dd = ""

[[doc.html.body.main.dl.div]]
attrib = { class = "number field" }
dt = "Number"
dd = ""

[[doc.html.body.main.dl.div]]
attrib = { class = "mass field" }
dt = "Atomic Mass"
dd = ""
