# https://raw.githubusercontent.com/Bowserinator/Periodic-Table-JSON/refs/heads/master/periodic-table-lookup.json

[metadata]

[doc]
config = {tag_mode = "open"}
"!doctype html" = ""

[doc.html]
config = {tag_mode = "pair"}
attrib = {lang = "en"}

[doc.html.head]
title = "{metadata[title]}"

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {charset = "UTF-8"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {name = "viewport", content = "width=device-width, initial-scale=1.0"}

[[doc.html.head.meta]]
config = {tag_mode = "void"}
attrib = {http-equiv = "X-UA-Compatible", content = "ie=edge"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "preconnect", href = "https://fonts.googleapis.com"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = "crossorigin"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "stylesheet", href="https://fonts.googleapis.com/css2?family=Bitter:ital,wght@0,100..900;1,100..900&display=swap"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel = "stylesheet", href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&display=swap"}

[[doc.html.head.link]]
config = {tag_mode = "void"}
attrib = {rel= "stylesheet", href="basics.css"}

[[doc.html.head.script]]
attrib = {src = "https://unpkg.com/hyperscript.org@0.9.14", async = "async"}

[[doc.html.body.main.section]]
button = "Fetch data"

[doc.html.body.main.section.attrib]
id = "btn_fetch"
script = """
on click
add @disabled
fetch https://raw.githubusercontent.com/Bowserinator/Periodic-Table-JSON/refs/heads/master/periodic-table-lookup.json
as json
set global data to result
log data
put data["order"] after me
finally
remove @disabled
"""

[[doc.html.body.main.section]]
input = ""

[doc.html.body.main.section.attrib]
id = "inp_pick"
script = """
on input
for word in data["order"]
if my.value is not empty and word contains my.value.toLowerCase()
log "Word: " + word
"""

[[doc.html.body.main.dl.div]]
dt = "Key"
dd = "Value"
