# Base is a template structure applied to each node doc
[base]
"!doctype" = "html"

[base.html.head]
title = "{metadata[title]}"

[[base.html.head.meta]]

# Doc is the index template itself
[doc.html.head]
title = "{metadata[node].parent}"
